# Generated by Django 4.1.3 on 2022-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0067_article_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Texte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
